---
title: National Digital Stewardship Alliance - Digital Library Federation
email: ndsa@diglib.org
description: 'maintain, and advance the capacity to preserve our nation''s digital
  resources for the benefit of present and future generations.

'
baseurl: ''
url: http://ndsa.diglib.org/
twitter_username: clirdlf
github_username: clirdlf
google-tracking-id: UA-9461551-2
paginate: 5
org_count: 210
exclude:
- ".gitignore"
- ".env"
- ".git"
- node_modules
- temp
- vendor
- gulpfile.js
- package.json
- README.md
sass:
  style: compressed
markdown: kramdown
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
